capability to create first free subnet
lord-kyron/terraform-provider-phpipam pull request #25
Opened 2020-10-04 16:15 UTC by tomasherout

Hello,

phpIPAM has capability to create _Creates new child subnet inside subnet with specified mask_ -  by API call `/api/my_app/subnets/{id}/first_subnet/{mask}/` - https://phpipam.net/api/api_documentation/

phpipam-sdk-go library also supports this since 3 months ago https://github.com/pavel-z1/phpipam-sdk-go/blob/master/controllers/subnets/subnets.go#L121

My fork tries to implement it together. Subnet can be created in current way (specify subnet address and mask):

```terraform
resource "phpipam_subnet" "s1" {
  section_id = data.phpipam_section.section.section_id
  subnet_address = "10.0.0.0"
  subnet_mask = 24
}
```
or in new way by specifing new **parent_subnet_id** option:

```terraform
resource "phpipam_subnet" "s1" {
  section_id = data.phpipam_section.section.section_id
  parent_subnet_id = 12
  subnet_mask = 24
}
```

Thanks for watching it and I hope it can be merged :)

2020-10-16 09:24 UTC, pavel-z1 commented
Hi @tomasherout ,
Please remove from commit files: go.mod, go.sum.

We have plans to update modules version shortly. They will conflict with modules versions from this PR.

2020-10-16 09:31 UTC, pavel-z1 requested changes

2020-10-16 09:31 UTC, pavel-z1 commented on plugin/providers/phpipam/resource_phpipam_subnet.go
> +	"github.com/pavel-z1/phpipam-sdk-go/phpipam"
I guess that in here you can not indicate the dependence from phpipam-sdk-go.
Try to remove this line please.

2020-10-17 14:41 UTC, lord-kyron commented
@pavel-z1  - does it look right to you now?

2020-10-19 06:13 UTC, pavel-z1 commented
Hi @lord-kyron , it's fine for me.

2020-10-19 06:14 UTC, pavel-z1 approved these changes

2020-10-19 06:15 UTC, merged

2020-10-19 06:15 UTC, pavel-z1 commented
Thank you @tomasherout for help.