Use terraform sdk v2 and support importing resources
lord-kyron/terraform-provider-phpipam pull request #51
Opened 2022-11-20 17:41 UTC by cristicalin

This PR updates the provider to use the terraform v2 sdk and implements the ability to use `terraform import` to import pre-created resources from existing phpipam installations.

2022-11-28 07:28 UTC, cristicalin commented
@lord-kyron could you take a look at this proposed change?

2022-12-14 16:25 UTC, pavel-z1 requested changes
First of all, thank you for the work you have done!

Please delete the directory **pkg**. The binary files will be added to the release assets.

In some files need to fix indent. Please format go files with this command to fix indent:
```
gofmt -w plugin/providers/phpipam/*
```

2022-12-14 16:25 UTC, pavel-z1 commented on plugin/providers/phpipam/data_source_phpipam_address.go
> +    } else {
I don't get the point of this change. Can you please add a comment why this check is needed?

2022-12-14 16:25 UTC, pavel-z1 commented on plugin/providers/phpipam/data_source_phpipam_subnet.go
> +    } else {
I don't get the point of this change. Can you please add a comment why this check is needed?

2022-12-19 10:10 UTC, cristicalin commented
Hi @pavel-z1, thanks for the review, I made the modifications you requested and explained why I needed to modify the import logic to ensure we don't destroy imported resources.

2022-12-21 12:27 UTC, pavel-z1 commented
Hi @cristicalin !
Thank you for updates


Format please these files and I will merge PR
```
# go fmt ./plugin/providers/phpipam/*
plugin/providers/phpipam/data_source_phpipam_address.go
plugin/providers/phpipam/data_source_phpipam_subnet.go
```

2022-12-28 08:41 UTC, cristicalin commented
@pavel-z1 I `go fmt`'ed the two files

2022-12-29 19:19 UTC, pavel-z1 approved these changes

2022-12-29 19:21 UTC, merged

2022-12-29 19:21 UTC, pavel-z1 commented
Thank you @cristicalin !
PR merged